// <auto-generated />
namespace RentACar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateTablo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateTablo));
        
        string IMigrationMetadata.Id
        {
            get { return "202212091252485_updateTablo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
